apiVersion: v1
kind: ServiceAccount
metadata:
  name: hiveadmission-cert-issuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hiveadmission-cert-issuer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hiveadmission-cert-issuer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hiveadmission-cert-issuer
subjects:
- kind: ServiceAccount
  name: hiveadmission-cert-issuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hiveadmission-cert-issuer
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["get", "create", "patch", "delete"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["beta.eks.amazonaws.com/app-serving"]
  verbs: ["approve"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hiveadmission-cert-issuer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hiveadmission-cert-issuer
subjects:
- kind: ServiceAccount
  name: hiveadmission-cert-issuer
  namespace: hive
