apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/waggle-io/waggle-hub
    targetRevision: main
    path: apps/hive
  destination:
    name: in-cluster
    namespace: hive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    # Hive CRDs exceed the client-side apply annotation size limit
    - ServerSideApply=true
