#!/usr/bin/env bash
# Renders Hive ClusterImageSets from apps/hive/clusterimagesets/versions.yaml.
#
# For each offered minor it takes the newest `keepPerMinor` releases in the
# <channel>-<minor> channel of the OpenShift update graph, pinned by digest.
# Versions that drop out of the window are kept but labelled
# waggle.io/offered=false, so ClusterDeployments that reference them still
# resolve. Fails if an offered minor is past the end of maintenance support.
#
# Output is deterministic: an unchanged upstream produces no diff.
# Requires: bash, curl, jq, yq (mikefarah v4).
#
# Usage: hack/gen-clusterimagesets.sh [warnings-file]
#   warnings-file: optional path; end-of-life warnings are written there
#   (used as the PR body by the workflow).
set -euo pipefail
export LC_ALL=C

ROOT=$(cd "$(dirname "$0")/.." && pwd)
DIR="$ROOT/apps/hive/clusterimagesets"
CONFIG="$DIR/versions.yaml"
WARNINGS_FILE="${1:-/dev/null}"
GRAPH_URL=https://api.openshift.com/api/upgrades_info/v1/graph
LIFECYCLE_URL='https://access.redhat.com/product-life-cycles/api/v1/products?name=OpenShift%20Container%20Platform%204'

channel=$(yq '.channel' "$CONFIG")
arch=$(yq '.arch' "$CONFIG")
keep=$(yq '.keepPerMinor' "$CONFIG")
default_minor=$(yq '.default' "$CONFIG")
warn_days=$(yq '.warnDaysBeforeEOL' "$CONFIG")
minors=$(yq '.minors[]' "$CONFIG")

case "$arch" in
  amd64) name_arch=x86-64 ;;
  arm64) name_arch=aarch64 ;;
  multi) name_arch=multi ;;
  *) echo "unsupported arch: $arch" >&2; exit 1 ;;
esac

if ! grep -qx "$default_minor" <<<"$minors"; then
  echo "default minor $default_minor is not in minors" >&2
  exit 1
fi

lifecycle=$(curl -fsSL "$LIFECYCLE_URL")
: >"$WARNINGS_FILE"
selected=()

for minor in $minors; do
  # End of maintenance support for this minor (YYYY-MM-DD)
  eol=$(jq -r --arg v "$minor" '
    .data[0].versions[] | select(.name == $v) | .phases[]
    | select(.name == "Maintenance support") | .date' <<<"$lifecycle")
  if [[ -z "$eol" || "$eol" == "N/A" ]]; then
    echo "no maintenance-support end date for $minor in the lifecycle API" >&2
    exit 1
  fi
  eol_date=${eol:0:10}
  days_left=$(jq -n --arg d "$eol_date" '(($d + "T00:00:00Z" | fromdateiso8601) - now) / 86400 | floor')
  if (( days_left < 0 )); then
    echo "OpenShift $minor left maintenance support on $eol_date; remove it from versions.yaml" >&2
    exit 1
  fi
  if (( days_left <= warn_days )); then
    echo "- OpenShift $minor leaves maintenance support on $eol_date ($days_left days); plan to drop it from versions.yaml" | tee -a "$WARNINGS_FILE" >&2
  fi

  graph=$(curl -fsSL -H 'Accept: application/json' "$GRAPH_URL?channel=$channel-$minor&arch=$arch")
  releases=$(jq -c --arg m "$minor." --argjson keep "$keep" '
    [.nodes[] | select(.version | startswith($m))]
    | sort_by(.version | split(".")[2] | tonumber)
    | .[-$keep:] | .[]
    | {version, payload, errata: (.metadata.url // "")}' <<<"$graph")
  if [[ -z "$releases" ]]; then
    echo "no $minor releases in $channel-$minor ($arch)" >&2
    exit 1
  fi
  newest=$(tail -n1 <<<"$releases" | jq -r .version)

  while read -r rel; do
    version=$(jq -r .version <<<"$rel")
    name="openshift-$version-$name_arch"
    is_default=false
    [[ "$minor" == "$default_minor" && "$version" == "$newest" ]] && is_default=true
    selected+=("$name")

    VERSION="$version" MINOR="$minor" CHANNEL="$channel" NAME="$name" \
    PAYLOAD=$(jq -r .payload <<<"$rel") ERRATA=$(jq -r .errata <<<"$rel") \
    DEFAULT="$is_default" EOL="$eol_date" \
    yq -n '
      .apiVersion = "hive.openshift.io/v1" |
      .kind = "ClusterImageSet" |
      .metadata.name = strenv(NAME) |
      .metadata.labels."waggle.io/minor" = strenv(MINOR) |
      .metadata.labels."waggle.io/channel" = strenv(CHANNEL) |
      .metadata.labels."waggle.io/offered" = "true" |
      .metadata.labels."waggle.io/default" = strenv(DEFAULT) |
      .metadata.annotations."waggle.io/version" = strenv(VERSION) |
      .metadata.annotations."waggle.io/errata" = strenv(ERRATA) |
      .metadata.annotations."waggle.io/support-ends" = strenv(EOL) |
      .spec.releaseImage = strenv(PAYLOAD)
    ' >"$DIR/$name.yaml"
  done <<<"$releases"
done

# Retire anything no longer selected, but keep the file
for f in "$DIR"/openshift-*.yaml; do
  [[ -e "$f" ]] || continue
  name=$(basename "$f" .yaml)
  if ! printf '%s\n' "${selected[@]}" | grep -qx "$name"; then
    yq -i '.metadata.labels."waggle.io/offered" = "false" | .metadata.labels."waggle.io/default" = "false"' "$f"
  fi
done

# Kustomization listing every ClusterImageSet, offered or retired
{
  cat <<'EOF'
# Generated by hack/gen-clusterimagesets.sh. Do not edit; change versions.yaml.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  # The ClusterImageSet CRD is created in the same sync
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
EOF
  for f in "$DIR"/openshift-*.yaml; do
    if [[ -e "$f" ]]; then echo "- $(basename "$f")"; fi
  done
} >"$DIR/kustomization.yaml"

echo "offered: ${selected[*]}"
