apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-4.21.35-x86-64
  labels:
    waggle.io/minor: "4.21"
    waggle.io/channel: stable
    waggle.io/offered: "true"
    waggle.io/default: "true"
  annotations:
    waggle.io/version: 4.21.35
    waggle.io/errata: https://access.redhat.com/errata/RHSA-2026:71453
    waggle.io/support-ends: "2027-08-03"
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release@sha256:1f8f423477982ce16193469c26f8941ba797a6f4fc3b3621a5d426ae19deb457
