apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd/argocd.yaml
- certmanager/certmanager.yaml
- externalsecrets/externalsecrets.yaml
- hive/hive.yaml
- clusters/appproject.yaml
- clusters/applicationset.yaml
